# Internal distro identifier
DISTRO = "ember"

# Human-readable display name
DISTRO_NAME = "Ember"

# Distro version string
DISTRO_VERSION = "1.0.0"

# Required for USB to TTL connection
ENABLE_UART = "1"
SERIAL_CONSOLES = "115200;ttyAMA0"

# Provides support for creating packages that use the Debian(.deb) file format
PACKAGE_CLASSES = "package_deb"

# Distro features
DISTRO_FEATURES:append = " systemd usrmerge"

# Init system
INIT_MANAGER = "systemd"

# Additional image features
EXTRA_IMAGE_FEATURES:append = " allow-root-login empty-root-password"

LICENSE_FLAGS_ACCEPTED:append = "synaptics-killswitch"
