# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-ember"
BBFILE_PATTERN_meta-ember = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-ember = "6"

LAYERDEPENDS_meta-ember = "core"
LAYERSERIES_COMPAT_meta-ember = "wrynose"
